import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { adminApi } from '../api';
import { ErrorBanner, PageHeader, RemoteTable, secondaryButtonClass } from '../components/RemoteTable';
type Fine = { _id:string; fineId:string; driverId:unknown; amount:number; reason?:string; status:string; createdAt:string };
export function FinesPage(){
 const [rows,setRows]=useState<Fine[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const response=await adminApi.fines();setRows(response.data.requests||[]);setError('');}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):'Unexpected error');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const action=async(item:Fine,type:'review'|'approve'|'reject')=>{const note=(type==='reject'?window.prompt('Rejection reason'):window.prompt('Optional review note'))||'';if(type==='reject'&&!note)return;try{if(type==='review')await adminApi.reviewFine(item._id);if(type==='approve')await adminApi.approveFine(item._id,note);if(type==='reject')await adminApi.rejectFine(item._id,note);await load();}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):'Unexpected error');}};
 return <section><PageHeader title="Fine requests" description="Review, approve, or reject submitted fine requests." />{error?<ErrorBanner message={error} retry={load}/>:null}<RemoteTable heads={['Fine','Driver','Amount','Reason','Status','Created','Actions']} loading={loading} empty={!rows.length}>{rows.map(item=><tr key={item._id} className="border-t border-white/5"><td className="py-4 pr-4">{item.fineId}</td><td className="py-4 pr-4">{typeof item.driverId==='object'?JSON.stringify(item.driverId):String(item.driverId)}</td><td className="py-4 pr-4">{item.amount}</td><td className="py-4 pr-4">{item.reason||'—'}</td><td className="py-4 pr-4">{item.status}</td><td className="py-4 pr-4">{new Date(item.createdAt).toLocaleDateString()}</td><td>{['pending','under_review'].includes(item.status)?<div className="flex gap-2">{item.status==='pending'?<button className={secondaryButtonClass} onClick={()=>action(item,'review')}>Review</button>:null}<button className={secondaryButtonClass} onClick={()=>action(item,'approve')}>Approve</button><button className={secondaryButtonClass} onClick={()=>action(item,'reject')}>Reject</button></div>:'—'}</td></tr>)}</RemoteTable></section>;
}
