import { FormEvent, useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { Link, useParams } from 'react-router-dom';
import { adminApi, type UserRecord } from '../api';
import { useAuth } from '../auth';
import { ErrorBanner, PageHeader, buttonClass, inputClass, secondaryButtonClass } from '../components/RemoteTable';
type Item=Record<string,unknown>; type Data={user:UserRecord&Record<string,unknown>;driverProfile:Item|null;passengerKyc:Item|null;driverKyc:Item|null;uploads:Item[];rides:Item[];transactions:Item[];loans:Item[];fines:Item[];fineRequests:Item[];wallet:Item|null;auditLogs:Item[]};
const sections=['overview','personal','kyc','rides','transactions','loans','logs'] as const; type Section=typeof sections[number];
const messageOf=(error:unknown)=>axios.isAxiosError(error)?String(error.response?.data?.message||error.message):'Unexpected error';
const show=(value:unknown)=>value===null||value===undefined||value===''?'—':typeof value==='object'?JSON.stringify(value):String(value);
function DataTable({rows,fields}:{rows:Item[];fields:string[]}){return <div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{fields.map(field=><th key={field} className="p-3 capitalize text-slate-500">{field.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row._id||index)} className="border-t border-white/5">{fields.map(field=><td key={field} className="max-w-xs truncate p-3">{show(row[field])}</td>)}</tr>)}</tbody></table>{!rows.length?<p className="p-6 text-center text-slate-500">No records.</p>:null}</div>}
export function IdentityWorkspace({driverOnly=false}:{driverOnly?:boolean}){
 const{id=''}=useParams();const{can}=useAuth();const[data,setData]=useState<Data|null>(null);const[section,setSection]=useState<Section>('overview');const[error,setError]=useState('');const[success,setSuccess]=useState('');const[loading,setLoading]=useState(true);const[walletSubmitting,setWalletSubmitting]=useState(false);const[form,setForm]=useState<Record<string,unknown>>({});const[walletAmount,setWalletAmount]=useState('');const[walletReason,setWalletReason]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await adminApi.userOverview(id);const next=response.data.data as Data;setData(next);setForm({firstName:next.user.firstName,lastName:next.user.lastName,phone:next.user.phone,email:next.user.email||'',isActive:next.user.isActive,isVerified:next.user.isVerified,isEmailVerified:next.user.isEmailVerified,kycLevel:next.user.kycLevel,registrationStatus:next.user.registrationStatus||'pending'});}catch(e){setError(messageOf(e));}finally{setLoading(false);}},[id]);
 useEffect(()=>{void load();},[load]); useEffect(()=>{if(!driverOnly)return;const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer);},[driverOnly,load]);
 const saveUser=async(e:FormEvent)=>{e.preventDefault();try{await adminApi.updateUser(id,form);await load();}catch(err){setError(messageOf(err));}};
 const saveProfile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));try{await adminApi.updateDriverProfile(id,payload);await load();}catch(err){setError(messageOf(err));}};
 const topUpWallet=async(e:FormEvent)=>{e.preventDefault();const amount=Number(walletAmount);const reason=walletReason.trim();setError('');setSuccess('');if(!Number.isSafeInteger(amount)||amount<=0){setError('Enter a positive whole-number top-up amount.');return;}if(reason.length<5){setError('Enter a reason of at least 5 characters.');return;}if(!window.confirm(`Top up ${amount.toLocaleString()} RWF to ${u.firstName} ${u.lastName}?`))return;setWalletSubmitting(true);try{await adminApi.adjustUserWallet(id,amount,reason,crypto.randomUUID());setWalletAmount('');setWalletReason('');setSuccess(`Wallet topped up by ${amount.toLocaleString()} RWF.`);await load();}catch(err){setError(messageOf(err));}finally{setWalletSubmitting(false);}};
 if(loading&&!data)return <p>Loading identity workspace…</p>;if(!data)return <>{error?<ErrorBanner message={error} retry={load}/>:null}</>;
 const u=data.user;const location=u.lastLocation as {latitude?:number;longitude?:number}|undefined;const lat=location?.latitude;const lng=location?.longitude;const mapUrl=lat!==undefined&&lng!==undefined?`https://www.openstreetmap.org/export/embed.html?bbox=${lng-.01}%2C${lat-.01}%2C${lng+.01}%2C${lat+.01}&layer=mapnik&marker=${lat}%2C${lng}`:'';
 return <section><PageHeader title={`${u.firstName} ${u.lastName}`} description={`${u.role} • ${u.phone} • account ${u._id}`} action={<Link to={driverOnly?'/drivers':'/users'} className={secondaryButtonClass}>Back to list</Link>}/>{error?<ErrorBanner message={error} retry={load}/>:null}{success?<p role="status" className="mb-4 rounded-xl border border-lime/30 bg-lime/10 p-4 text-sm text-lime">{success}</p>:null}<div className="mb-6 flex gap-2 overflow-x-auto">{sections.map(item=><button key={item} onClick={()=>setSection(item)} className={section===item?buttonClass:secondaryButtonClass}>{item}</button>)}</div>
 {section==='overview'?<div className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-panel p-6"><h3 className="font-semibold">Account status</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-500">Role</dt><dd>{u.role}</dd><dt className="text-slate-500">Active</dt><dd>{show(u.isActive)}</dd><dt className="text-slate-500">Phone verified</dt><dd>{show(u.isVerified)}</dd><dt className="text-slate-500">Email verified</dt><dd>{show(u.isEmailVerified)}</dd><dt className="text-slate-500">Registration</dt><dd>{show(u.registrationStatus)}</dd><dt className="text-slate-500">KYC</dt><dd>{u.kycLevel}</dd></dl></article><article className="rounded-2xl border border-white/10 bg-panel p-6"><h3 className="font-semibold">Wallet</h3><p className="mt-3 text-3xl font-semibold">{show(data.wallet?.balance)} <small className="text-sm text-slate-500">RWF</small></p>{u.role==='driver'?<p className="mt-2 text-sm text-slate-400">{show(data.driverProfile?.plateNumber)} • {show(u.isOnline?'Online':'Offline')} • GPS {show(u.lastLocationAt)}</p>:<p className="mt-2 text-sm text-slate-400">Top-ups are recorded in the user's transactions and audit log.</p>}{can('wallet:adjust')?<form onSubmit={topUpWallet} className="mt-5 grid gap-3"><label className="text-sm">Top-up amount (RWF)<input required type="number" min="1" step="1" inputMode="numeric" className={`${inputClass} mt-1`} placeholder="100000" value={walletAmount} onChange={e=>setWalletAmount(e.target.value)}/></label><label className="text-sm">Reason<input required minLength={5} maxLength={250} className={`${inputClass} mt-1`} placeholder="Manual wallet top-up" value={walletReason} onChange={e=>setWalletReason(e.target.value)}/></label><button disabled={walletSubmitting} className={`${buttonClass} disabled:cursor-not-allowed disabled:opacity-50`}>{walletSubmitting?'Processing…':'Top up wallet'}</button></form>:<p className="mt-5 text-sm text-slate-500">Your role does not have wallet adjustment permission.</p>}</article>{driverOnly&&mapUrl?<article className="overflow-hidden rounded-2xl border border-white/10 bg-panel xl:col-span-2"><div className="p-4"><h3 className="font-semibold">Live driver position</h3><p className="text-xs text-slate-500">Refreshes every 15 seconds • {lat}, {lng}</p></div><iframe title="Driver location on OpenStreetMap" src={mapUrl} className="h-96 w-full border-0" loading="lazy"/></article>:null}</div>:null}
 {section==='personal'?<form onSubmit={saveUser} className="grid gap-4 rounded-2xl border border-white/10 bg-panel p-6 md:grid-cols-2">{['firstName','lastName','phone','email'].map(field=><label key={field} className="text-sm capitalize">{field}<input className={`${inputClass} mt-1`} value={String(form[field]||'')} onChange={e=>setForm(v=>({...v,[field]:e.target.value}))}/></label>)}{['isActive','isVerified','isEmailVerified'].map(field=><label key={field} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form[field])} onChange={e=>setForm(v=>({...v,[field]:e.target.checked}))}/>{field}</label>)}<label className="text-sm">KYC<select className={`${inputClass} mt-1`} value={String(form.kycLevel)} onChange={e=>setForm(v=>({...v,kycLevel:e.target.value}))}><option className="bg-ink">basic</option><option className="bg-ink">full</option></select></label><label className="text-sm">Registration<select className={`${inputClass} mt-1`} value={String(form.registrationStatus)} onChange={e=>setForm(v=>({...v,registrationStatus:e.target.value}))}>{['pending','correction','approved'].map(v=><option className="bg-ink" key={v}>{v}</option>)}</select></label>{can('user:update')?<button className={buttonClass}>Save account</button>:null}</form>:null}
 {section==='kyc'?<div className="space-y-5"><article className="rounded-2xl border border-white/10 bg-panel p-6"><h3 className="font-semibold">KYC documents</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{data.uploads.map(file=><a key={String(file._id)} href={String(file.url)} target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 p-4 text-lime">View {show(file.format)} attachment</a>)}{data.driverProfile?.insuranceAttachment?<a href={String(data.driverProfile.insuranceAttachment)} target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 p-4 text-lime">View insurance</a>:null}{data.driverProfile?.permitAttachment?<a href={String(data.driverProfile.permitAttachment)} target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 p-4 text-lime">View permit</a>:null}{!data.uploads.length&&!data.driverProfile?.insuranceAttachment?<p className="text-slate-500">No attachments.</p>:null}</div></article>{data.driverProfile&&can('driver:update')?<form onSubmit={saveProfile} className="grid gap-3 rounded-2xl border border-white/10 bg-panel p-6 md:grid-cols-2">{['plateNumber','cooperativeName','nid','permitId','code','insuranceAttachment','permitAttachment'].map(field=><label key={field} className="text-sm">{field}<input name={field} defaultValue={String(data.driverProfile?.[field]||'')} className={`${inputClass} mt-1`}/></label>)}<button className={buttonClass}>Save driver profile</button></form>:null}</div>:null}
 {section==='rides'?<DataTable rows={data.rides} fields={['_id','rideStatus','paymentStatus','fare','createdAt']}/>:null}{section==='transactions'?<DataTable rows={data.transactions} fields={['_id','type','amount','status','reference','createdAt']}/>:null}{section==='loans'?<div className="space-y-6"><DataTable rows={data.loans} fields={['_id','loanAmount','remainingBalance','loanStatus','createdAt']}/><DataTable rows={data.fines} fields={['fineId','amount','status','paidAmount','createdAt']}/><DataTable rows={data.fineRequests} fields={['fineId','amount','status','reason','createdAt']}/></div>:null}{section==='logs'?<DataTable rows={data.auditLogs} fields={['action','actorRole','targetType','ipAddress','timestamp']}/>:null}</section>;
}
export function UserDetailPage(){return <IdentityWorkspace/>} export function DriverDetailPage(){return <IdentityWorkspace driverOnly/>}
