import{useState}from'react';import{groups,templates,type StaffRole}from'../permissions';
const events=[['Eric N.','Approved driver registration','Driver RW-4281','2 min'],['Diane U.','Synchronized transaction','TX 98KX21','11 min'],['Sarah I.','Added customer call note','Passenger +250 78•••129','18 min'],['Patrick K.','Approved fine request','Fine F-1042','31 min']];
const Card=({label,value,detail}:{label:string;value:string;detail:string})=><div className="rounded-2xl border border-white/10 bg-panel p-5"><div className="text-sm text-slate-400">{label}</div><div className="mt-5 text-3xl font-semibold">{value}</div><div className="mt-2 text-xs text-slate-500">{detail}</div></div>;
const Table=({heads,rows}:{heads:string[];rows:string[][]})=><div className="overflow-x-auto rounded-2xl border border-white/10 bg-panel p-5"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{heads.map(h=><th key={h} className="pb-4">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-white/5">{r.map((x,j)=><td key={j} className={`py-4 ${j===0?'font-medium':'text-slate-400'}`}>{x}</td>)}</tr>)}</tbody></table></div>;
export function OverviewPage(){return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Active rides" value="128" detail="+12% today"/><Card label="Online drivers" value="842" detail="78 nearby"/><Card label="Today’s volume" value="18.4M RWF" detail="+8.2%"/><Card label="Open cases" value="24" detail="6 urgent"/></div><div className="mt-6"><AuditPage/></div></>}
export function PeoplePage(){return <Table heads={['User','Role','Phone','Status','Joined']} rows={[["Aline Mukasa","Driver","+250 78•••123","Active","12 Sep"],["Jean Niyom","Passenger","+250 72•••845","Active","11 Sep"],["Grace Uwera","Agent","+250 79•••229","Review","10 Sep"]]}/>}
export function RidesPage(){return <Table heads={['Ride','Passenger','Driver','Status','Fare']} rows={[["RD-10842","Jean N.","Aline M.","In progress","4,800 RWF"],["RD-10841","Grace U.","Patrick K.","Completed","3,200 RWF"],["RD-10840","Eric N.","—","Searching","5,100 RWF"]]}/>}
export function FinancePage(){return <><div className="mb-6 grid gap-4 md:grid-cols-3"><Card label="Wallet liability" value="84.2M" detail="RWF"/><Card label="Settled today" value="12.8M" detail="RWF"/><Card label="Exceptions" value="5" detail="Need reconciliation"/></div><Table heads={['Transaction','User','Type','Amount','Status']} rows={[["TX-98KX21","Jean N.","Ride payment","4,800 RWF","Successful"],["TX-98KX20","Aline M.","Cash out","20,000 RWF","Pending"],["TX-98KX19","Grace U.","Wallet credit","8,500 RWF","Successful"]]}/></>}
export function RegistrationsPage(){return <Table heads={['Applicant','Type','Submitted','KYC','Action']} rows={[["Claude M.","Driver","16 Sep","Complete","Review"],["Odette K.","Agent","16 Sep","Needs document","Review"],["Mugisha P.","Driver","15 Sep","Complete","Review"]]}/>}
export function AuditPage(){return <section className="rounded-2xl border border-white/10 bg-panel p-6"><div className="mb-5 flex justify-between"><div><h2 className="font-semibold">Staff activity</h2><p className="text-sm text-slate-500">Who did what, where and when.</p></div><button className="rounded-xl border border-white/10 px-3 text-sm">Export CSV</button></div>{events.map(e=><div key={e[1]} className="grid gap-2 border-t border-white/5 py-4 text-sm md:grid-cols-[130px_1fr_1fr_80px]"><b>{e[0]}</b><span>{e[1]}</span><span className="text-slate-500">{e[2]}</span><span className="text-slate-600 md:text-right">{e[3]}</span></div>)}</section>}
const labels:Record<StaffRole,string>={superadmin:'Super admin',admin:'Admin',financial:'Financial',agent:'Agent',caller_support:'Caller support'};
export function RolesPage(){const[role,setRole]=useState<StaffRole>('admin');const[perms,setPerms]=useState(templates);const toggle=(p:string)=>setPerms(v=>({...v,[role]:v[role].includes(p)?v[role].filter(x=>x!==p):[...v[role],p]}));return <div className="grid gap-6 xl:grid-cols-[280px_1fr]"><aside className="space-y-2">{(Object.keys(labels)as StaffRole[]).map(r=><button key={r} onClick={()=>setRole(r)} className={`w-full rounded-xl border p-4 text-left ${role===r?'border-lime bg-lime/5':'border-white/10 bg-panel'}`}><b>{labels[r]}</b><span className="float-right text-xs text-slate-500">{perms[r].length}</span></button>)}</aside><section className="rounded-2xl border border-white/10 bg-panel p-6"><div className="mb-6 flex justify-between"><div><h2 className="text-lg font-semibold">{labels[role]} permissions</h2><p className="text-sm text-slate-500">All changes must be audited by the backend.</p></div><button className="rounded-xl bg-lime px-4 text-sm font-bold text-ink">Save</button></div>{Object.entries(groups).map(([group,list])=><div key={group} className="mb-7"><h3 className="mb-3 text-sm font-semibold">{group}</h3><div className="grid gap-2 md:grid-cols-2">{list.map(p=><label key={p} className="flex gap-3 rounded-xl border border-white/5 p-3"><input type="checkbox" checked={perms[role].includes(p)} disabled={role==='superadmin'} onChange={()=>toggle(p)} className="accent-[#c8f04b]"/><span className="text-sm">{p}</span></label>)}</div></div>)}</section></div>}
export function SettingsPage(){return <div className="grid gap-5 lg:grid-cols-2">{[['General settings','Application name, support contacts and maintenance mode.'],['Financial controls','Fees, commissions, loan limits and settlement rules.'],['Notification channels','Email, SMS and push delivery configuration.'],['Security','Sessions, access policies and audit retention.']].map(([h,p])=><section key={h} className="rounded-2xl border border-white/10 bg-panel p-6"><h2 className="font-semibold">{h}</h2><p className="mt-2 text-sm text-slate-500">{p}</p><button className="mt-5 rounded-xl border border-white/10 px-4 py-2 text-sm">Configure</button></section>)}</div>}
