import { useState, type FormEvent } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
export function LoginPage(){
 const {staff,login}=useAuth(); const navigate=useNavigate(); const location=useLocation(); const[identifier,setIdentifier]=useState(''); const[password,setPassword]=useState(''); const[error,setError]=useState(''); const[loading,setLoading]=useState(false);
 if(staff)return <Navigate to="/overview" replace/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await login(identifier,password);navigate((location.state as {from?:string})?.from||'/overview',{replace:true});}catch(err:unknown){const value=err as {response?:{data?:{message?:string}};message?:string};setError(value.response?.data?.message||value.message||'Unable to sign in');}finally{setLoading(false);}};
 return <main className="grid min-h-screen place-items-center p-5"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-panel p-8 shadow-glow"><div className="mb-8 text-center"><img src="/mota-logo.png" alt="MOTA — Rider’s best friend" className="mx-auto h-28 w-auto object-contain"/><h1 className="mt-4 text-xl font-bold">MOTA Control</h1><p className="text-sm text-slate-500">Authorized staff access only</p></div><label className="mb-2 block text-sm">Phone or email</label><input required value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" className="mb-5 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-lime"/><label className="mb-2 block text-sm">Password</label><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-lime"/>{error?<p role="alert" className="mt-4 text-sm text-rose-400">{error}</p>:null}<button disabled={loading} className="mt-6 w-full rounded-xl bg-lime py-3 font-bold text-ink disabled:opacity-50">{loading?'Signing in…':'Sign in'}</button></form></main>;
}
