import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { adminApi } from '../api';
import { ErrorBanner, PageHeader, RemoteTable, secondaryButtonClass } from '../components/RemoteTable';

const message = (error: unknown) => axios.isAxiosError(error) ? String(error.response?.data?.message || error.message) : 'Unexpected error';
export function SafetyDisputesPage() {
  const [safety, setSafety] = useState<any[]>([]); const [disputes, setDisputes] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [a, b] = await Promise.all([adminApi.safetyEvents(), adminApi.rideDisputes()]); setSafety(a.data.data || []); setDisputes(b.data.data || []); setError(''); } catch (e) { setError(message(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const updateSafety = async (id: string, status: string) => { try { await adminApi.updateSafetyEvent(id, { status }); await load(); } catch (e) { setError(message(e)); } };
  const updateDispute = async (id: string, status: string, refundStatus?: string) => { try { await adminApi.updateRideDispute(id, { status, ...(refundStatus ? { refundStatus } : {}) }); await load(); } catch (e) { setError(message(e)); } };
  return <section className="space-y-8"><PageHeader title="Safety & disputes" description="A production queue for urgent safety events, ride investigations, and refund decisions."/>{error ? <ErrorBanner message={error} retry={load}/> : null}<div><h2 className="mb-3 text-lg font-semibold">Safety events</h2><RemoteTable heads={['Event','Customer','Ride','Location','Status','Action']} loading={loading} empty={!safety.length}>{safety.map((item) => <tr key={item._id} className="border-t border-white/5"><td className="py-4 pr-4"><b className="capitalize">{item.type}</b><div className="text-xs text-slate-500">{item.category || 'General'}</div></td><td className="py-4 pr-4">{item.reporterId ? `${item.reporterId.firstName} ${item.reporterId.lastName}` : '—'}</td><td className="py-4 pr-4">{item.rideId?._id?.slice(-8) || '—'}</td><td className="py-4 pr-4">{item.location?.latitude != null ? `${item.location.latitude.toFixed(5)}, ${item.location.longitude.toFixed(5)}` : '—'}</td><td className="py-4 pr-4 capitalize">{item.status}</td><td className="space-x-2"><button className={secondaryButtonClass} onClick={() => updateSafety(item._id, 'acknowledged')}>Acknowledge</button><button className={secondaryButtonClass} onClick={() => updateSafety(item._id, 'resolved')}>Resolve</button></td></tr>)}</RemoteTable></div><div><h2 className="mb-3 text-lg font-semibold">Ride disputes and refunds</h2><RemoteTable heads={['Ride','Opened by','Category','Status','Refund','Action']} loading={loading} empty={!disputes.length}>{disputes.map((item) => <tr key={item._id} className="border-t border-white/5"><td className="py-4 pr-4">{item.rideId?._id?.slice(-8) || '—'}</td><td className="py-4 pr-4">{item.openedBy ? `${item.openedBy.firstName} ${item.openedBy.lastName}` : '—'}</td><td className="py-4 pr-4 capitalize">{item.category}</td><td className="py-4 pr-4 capitalize">{item.status}</td><td className="py-4 pr-4 capitalize">{item.refund?.status}</td><td className="space-x-2"><button className={secondaryButtonClass} onClick={() => updateDispute(item._id, 'investigating')}>Investigate</button>{item.refund?.requested ? <button className={secondaryButtonClass} onClick={() => updateDispute(item._id, 'resolved', 'approved')}>Approve refund</button> : null}<button className={secondaryButtonClass} onClick={() => updateDispute(item._id, 'resolved')}>Resolve</button></td></tr>)}</RemoteTable></div></section>;
}
