import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Pencil, Plus, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react';
import { adminApi, type RoleRecord, type UserInput, type UserRecord } from '../api';
import { useAuth } from '../auth';
import { ErrorBanner, PageHeader, RemoteTable, buttonClass, inputClass, secondaryButtonClass } from '../components/RemoteTable';

const roles = ['client', 'driver', 'agent', 'caller_support', 'financial', 'admin', 'superadmin'];
const blank: UserInput = { firstName: '', lastName: '', phone: '', email: '', password: '', role: 'client', isActive: true, isVerified: false, kycLevel: 'basic' };
const messageOf = (error: unknown) => axios.isAxiosError(error) ? String(error.response?.data?.message || error.message) : 'Unexpected error';

export function UsersPage() {
  const { can } = useAuth();
  const [users, setUsers] = useState<UserRecord[]>([]); const [roleRecords, setRoleRecords] = useState<RoleRecord[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<UserRecord | null>(null); const [form, setForm] = useState<UserInput>(blank); const [open, setOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [userResponse, roleResponse] = await Promise.all([adminApi.users({ limit: 100 }), adminApi.roles()]); setUsers(userResponse.data.data || []); setRoleRecords(roleResponse.data.data || roleResponse.data || []); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const value = query.trim().toLowerCase(); return value ? users.filter((user) => `${user.firstName} ${user.lastName} ${user.phone} ${user.email || ''} ${user.role}`.toLowerCase().includes(value)) : users; }, [query, users]);
  const showCreate = () => { setEditing(null); setForm(blank); setOpen(true); setNotice(''); };
  const showEdit = (user: UserRecord) => { setEditing(user); setForm({ firstName: user.firstName, lastName: user.lastName, phone: user.phone, email: user.email || '', role: user.role, roleId: typeof user.roleId === 'object' ? user.roleId._id : user.roleId, isActive: user.isActive, isVerified: user.isVerified, kycLevel: user.kycLevel }); setOpen(true); setNotice(''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const roleRecord = roleRecords.find((record) => record.name === form.role); const payload = { ...form, roleId: roleRecord?._id }; if (editing) { const originalRole = editing.role; await adminApi.updateUser(editing._id, payload); if (originalRole !== form.role) await adminApi.assignUserRole(editing._id, form.role, roleRecord?._id); setNotice('User updated successfully.'); } else { await adminApi.createUser(payload); setNotice('User created successfully.'); } setOpen(false); await load(); } catch (e) { setError(messageOf(e)); } finally { setSaving(false); } };
  const remove = async (user: UserRecord) => { if (!window.confirm(`Permanently delete ${user.firstName} ${user.lastName}? This cannot be undone.`)) return; try { await adminApi.deleteUser(user._id); setNotice('User deleted.'); await load(); } catch (e) { setError(messageOf(e)); } };
  const toggleActive = async (user: UserRecord) => { try { await adminApi.setUserActive(user._id, !user.isActive); setNotice(`User ${user.isActive ? 'deactivated' : 'activated'}.`); await load(); } catch (e) { setError(messageOf(e)); } };
  const verify = async (user: UserRecord) => { try { await adminApi.verifyUser(user._id); setNotice('User verified.'); await load(); } catch (e) { setError(messageOf(e)); } };
  return <section><PageHeader title="User management" description="Create, inspect, update, verify, activate, assign roles, and delete real platform accounts." action={can('user:create') ? <button onClick={showCreate} className={buttonClass}><Plus className="mr-2 inline" size={16}/>New user</button> : undefined}/>{error ? <ErrorBanner message={error} retry={load}/> : null}{notice ? <div role="status" className="mb-5 rounded-xl border border-lime/20 bg-lime/10 p-3 text-sm text-lime">{notice}</div> : null}<div className="mb-4 flex gap-3"><input aria-label="Search users" className={inputClass} placeholder="Search name, phone, email or role" value={query} onChange={(e) => setQuery(e.target.value)}/><button aria-label="Refresh users" className={secondaryButtonClass} onClick={load}><RefreshCw size={17}/></button></div><RemoteTable heads={['User', 'Contact', 'Role', 'KYC', 'Status', 'Created', 'Actions']} loading={loading} empty={!visible.length}>{visible.map((user) => <tr key={user._id} className="border-t border-white/5"><td className="py-4 pr-4 font-medium">{user.firstName} {user.lastName}</td><td className="py-4 pr-4 text-slate-400"><div>{user.phone}</div><div className="text-xs">{user.email || 'No email'}</div></td><td className="py-4 pr-4 capitalize">{user.role.replace('_', ' ')}</td><td className="py-4 pr-4 capitalize">{user.kycLevel}</td><td className="py-4 pr-4"><button disabled={!can('user:update')} onClick={() => toggleActive(user)} className={`rounded-full px-2.5 py-1 text-xs ${user.isActive ? 'bg-lime/15 text-lime' : 'bg-red-400/10 text-red-300'}`}>{user.isActive ? 'Active' : 'Inactive'}</button></td><td className="py-4 pr-4 text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</td><td className="py-4"><div className="flex gap-2">{can('user:verify') && !user.isVerified ? <button title="Verify user" className={secondaryButtonClass} onClick={() => verify(user)}><ShieldCheck size={15}/></button> : null}{can('user:update') ? <button title="Edit user" className={secondaryButtonClass} onClick={() => showEdit(user)}><Pencil size={15}/></button> : null}{can('user:delete') ? <button title="Delete user" className={secondaryButtonClass} onClick={() => remove(user)}><Trash2 size={15}/></button> : null}</div></td></tr>)}</RemoteTable>
  {open ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-panel p-6"><h3 className="text-xl font-semibold">{editing ? 'Edit user' : 'Create user'}</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{(['firstName','lastName','phone','email'] as const).map((field) => <label key={field} className="text-sm capitalize">{field.replace(/([A-Z])/g, ' $1')}<input required={field !== 'email'} className={`${inputClass} mt-1`} value={String(form[field] || '')} onChange={(e) => setForm((value) => ({ ...value, [field]: e.target.value }))}/></label>)}{!editing ? <label className="text-sm">Temporary password<input required minLength={8} type="password" autoComplete="new-password" className={`${inputClass} mt-1`} value={form.password || ''} onChange={(e) => setForm((value) => ({ ...value, password: e.target.value }))}/></label> : null}<label className="text-sm">Role<select className={`${inputClass} mt-1`} value={form.role} onChange={(e) => setForm((value) => ({ ...value, role: e.target.value }))}>{roles.map((role) => <option className="bg-ink" key={role} value={role}>{role.replace('_', ' ')}</option>)}</select></label><label className="text-sm">KYC level<select className={`${inputClass} mt-1`} value={form.kycLevel} onChange={(e) => setForm((value) => ({ ...value, kycLevel: e.target.value as 'basic'|'full' }))}><option className="bg-ink" value="basic">Basic</option><option className="bg-ink" value="full">Full</option></select></label><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={Boolean(form.isActive)} onChange={(e) => setForm((value) => ({ ...value, isActive: e.target.checked }))}/> Active</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className={secondaryButtonClass} onClick={() => setOpen(false)}>Cancel</button><button disabled={saving} className={buttonClass}>{saving ? 'Saving…' : 'Save user'}</button></div></form></div> : null}</section>;
}
