import{useState}from'react';
import{Activity,BarChart3,Bell,Car,CircleDollarSign,LayoutDashboard,Menu,Search,Settings,ShieldCheck,Users,X}from'lucide-react';
import{groups,templates,type StaffRole}from'./permissions';
type Page='Overview'|'People'|'Rides'|'Finance'|'Registrations'|'Staff & roles'|'Audit trail'|'Settings';
const nav:[Page,any][]=[['Overview',LayoutDashboard],['People',Users],['Rides',Car],['Finance',CircleDollarSign],['Registrations',ShieldCheck],['Staff & roles',Users],['Audit trail',Activity],['Settings',Settings]];
const meta:Record<StaffRole,{label:string;color:string;summary:string}>={superadmin:{label:'Super admin',color:'bg-violet-400',summary:'Full ownership, roles and sensitive configuration.'},admin:{label:'Admin',color:'bg-lime',summary:'Daily administration without ownership-only controls.'},financial:{label:'Financial',color:'bg-cyan-400',summary:'Wallets, payments, loans, reconciliation and refunds.'},agent:{label:'Agent',color:'bg-amber-400',summary:'Driver onboarding, KYC, vouchers and fines.'},caller_support:{label:'Caller support',color:'bg-rose-400',summary:'Customer context, support calls and notifications.'}};
const events=[['Eric N.','Approved driver registration','Driver RW-4281','2 min'],['Diane U.','Synchronized transaction','TX 98KX21','11 min'],['Sarah I.','Added customer call note','Passenger +250 78•••129','18 min'],['Patrick K.','Approved fine request','Fine F-1042','31 min'],['Aline M.','Changed role permissions','Financial role','1 hr']];

export default function App(){const[page,setPage]=useState<Page>('Overview');const[open,setOpen]=useState(false);const[role,setRole]=useState<StaffRole>('admin');const[perms,setPerms]=useState<Record<StaffRole,string[]>>(templates);return <div className="min-h-screen text-slate-100">
<aside className={`fixed inset-y-0 left-0 z-40 w-72 border-r border-white/10 bg-ink/95 p-5 backdrop-blur-xl transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime font-black text-ink">M</div><div><b>MOTA CONTROL</b><div className="text-xs text-slate-500">Operations console</div></div></div><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="space-y-1">{nav.map(([item,Icon])=><button key={item} onClick={()=>{setPage(item);setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-medium ${page===item?'bg-lime text-ink':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon size={18}/>{item}</button>)}</nav><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2 text-sm"><span className={`h-2 w-2 rounded-full ${meta[role].color}`}/>{meta[role].label}</div><div className="mt-2 text-xs text-slate-500">{perms[role].length} permissions active</div></div></aside>
<main className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-white/10 bg-ink/80 px-5 backdrop-blur-xl md:px-8"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div><h1 className="text-xl font-semibold">{page}</h1><p className="hidden text-xs text-slate-500 sm:block">Live operations and access control</p></div><div className="ml-auto flex items-center gap-3"><div className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 md:flex"><Search size={16}/><input aria-label="Search" placeholder="Search system" className="w-56 bg-transparent text-sm outline-none"/></div><button className="rounded-xl border border-white/10 p-2.5"><Bell size={18}/></button><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-700 text-sm font-bold">AM</div></div></header><div className="p-5 md:p-8">{page==='Overview'?<Overview/>:page==='Staff & roles'?<Roles role={role} setRole={setRole} perms={perms} setPerms={setPerms}/>:page==='Audit trail'?<Audit/>:<Module page={page}/>}</div></main></div>}

function Overview(){return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Active rides','128','+12%'],['Online drivers','842','78 nearby'],['Today’s volume','18.4M RWF','+8.2%'],['Open cases','24','6 urgent']].map(([l,v,d],i)=><div key={l} className="rounded-2xl border border-white/10 bg-panel p-5 shadow-glow"><div className="mb-5 flex justify-between text-sm text-slate-400">{l}<span className={`h-2 w-2 rounded-full ${i===3?'bg-amber-400':'bg-lime'}`}/></div><div className="text-3xl font-semibold">{v}</div><div className="mt-2 text-xs text-slate-500">{d}</div></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_1fr]"><section className="rounded-2xl border border-white/10 bg-panel p-6"><div className="mb-6 flex justify-between"><b>Network activity</b><BarChart3 className="text-lime"/></div><div className="flex h-52 items-end gap-2">{[42,66,52,78,63,86,73,91,58,84,76,94].map((h,i)=><div key={i} className="flex-1 rounded-t bg-gradient-to-t from-lime/30 to-lime" style={{height:`${h}%`}}/>)}</div></section><section className="rounded-2xl border border-white/10 bg-panel p-6"><b>Requires attention</b>{[['Registration reviews','17'],['Payment exceptions','5'],['Ride disputes','8'],['Support escalations','6']].map(([x,n])=><div key={x} className="flex border-b border-white/5 py-4 text-sm"><span className="flex-1">{x}</span><span className="text-lime">{n}</span></div>)}</section></div><div className="mt-6"><Audit/></div></>}

function Roles({role,setRole,perms,setPerms}:{role:StaffRole;setRole:(r:StaffRole)=>void;perms:Record<StaffRole,string[]>;setPerms:(x:Record<StaffRole,string[]>)=>void}){const toggle=(p:string)=>setPerms({...perms,[role]:perms[role].includes(p)?perms[role].filter(x=>x!==p):[...perms[role],p]});return <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><section className="space-y-3">{(Object.keys(meta)as StaffRole[]).map(r=><button onClick={()=>setRole(r)} key={r} className={`w-full rounded-2xl border p-4 text-left ${role===r?'border-lime/50 bg-lime/5':'border-white/10 bg-panel'}`}><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${meta[r].color}`}/><b>{meta[r].label}</b><span className="ml-auto text-xs text-slate-500">{perms[r].length}</span></div><p className="mt-2 text-sm text-slate-500">{meta[r].summary}</p></button>)}</section><section className="rounded-2xl border border-white/10 bg-panel p-6"><div className="mb-6 flex justify-between"><div><h2 className="text-lg font-semibold">{meta[role].label} permissions</h2><p className="text-sm text-slate-500">Every saved change must create an audit event.</p></div><button className="h-10 rounded-xl bg-lime px-4 text-sm font-bold text-ink">Save role</button></div><div className="space-y-7">{Object.entries(groups).map(([group,list])=><div key={group}><div className="mb-3 flex justify-between"><b className="text-sm">{group}</b><span className="text-xs text-slate-600">{list.filter(x=>perms[role].includes(x)).length}/{list.length}</span></div><div className="grid gap-2 md:grid-cols-2">{list.map(p=><label key={p} className="flex cursor-pointer gap-3 rounded-xl border border-white/5 bg-black/10 p-3"><input type="checkbox" checked={perms[role].includes(p)} disabled={role==='superadmin'} onChange={()=>toggle(p)} className="accent-[#c8f04b]"/><div><div className="text-sm">{p}</div><div className="text-xs text-slate-600">{describe(p)}</div></div></label>)}</div></div>)}</div></section></div>}

function Audit(){return <section className="rounded-2xl border border-white/10 bg-panel p-6"><div className="mb-5 flex justify-between"><div><b>Staff activity</b><p className="text-sm text-slate-500">Who did what, where and when. Events cannot be edited.</p></div><button className="rounded-xl border border-white/10 px-3 text-sm">Export CSV</button></div>{events.map(e=><div key={e[1]} className="grid gap-2 border-t border-white/5 py-4 text-sm md:grid-cols-[130px_1fr_1fr_80px]"><b>{e[0]}</b><span>{e[1]}</span><span className="text-slate-500">{e[2]}</span><span className="text-slate-600 md:text-right">{e[3]}</span></div>)}</section>}
function Module({page}:{page:Page}){return <div className="rounded-2xl border border-white/10 bg-panel p-8"><div className="mb-4 grid h-12 w-12 place-items-center rounded-xl bg-lime/10 text-lime"><ShieldCheck/></div><h2 className="text-xl font-semibold">{page} workspace</h2><p className="mt-2 max-w-xl text-slate-500">This API-ready module is permission-gated. It safely shows an empty state until the matching backend response is available.</p><button className="mt-6 rounded-xl bg-lime px-4 py-2 text-sm font-bold text-ink">Refresh data</button></div>}
const describe=(p:string)=>{const[a,b]=p.split(':');return`${b.replaceAll('_',' ')} access for ${a.replaceAll('_',' ')}`};
